application: topsitecounter
version: 3
runtime: python

handlers:
- url: /css
  static_dir: css

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /js
  static_dir: js

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: topsitecounter.py
